---
title: "Tidy data"
output: github_document
---

```{r}
library(tidyverse)
library(readr)
```

## PULSE data; switch from wide to long format

```{r}
pulse_df = 
  haven::read_sas("data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names() |> 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  ) |> 
  mutate(
    visit = replace(visit, visit == "bl", "00m")
  )
```

Import FAS litters and pups.

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv") |> 
  janitor::clean_names() |> 
  select(litter_number, gd0_weight, gd18_weight) |> 
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = "gd",
    values_to = "weight",
  ) |> 
  mutate(
    gd = case_match(
      gd,
      "gd0_weight" ~ 0,
      "gd18_weight" ~ 18
    )
  )
  
```

```{r}
pups_df = 
  read_csv("data/FAS_pups.csv")
pups_df = janitor::clean_names(pups_df)
```


## LotR example; the csv has 3 separate tables in one excel sheet
Import LoTR words data. Add movie name variable so we don't lose this information when we combine datasets.

```{r}
fellowship_df = 
  readxl::read_excel("data/LotR_Words.xlsx", range = "B3:D6") |> 
  mutate(movie = "fellowship")

two_towers_df = 
  readxl::read_excel("data/LotR_Words.xlsx", range = "F3:H6") |> 
  mutate(movie = "two towers")

return_of_king_df = 
  readxl::read_excel("data/LotR_Words.xlsx", range = "J3:L6") |> 
  mutate(movie = "return of the king")
```

Can stack these data sets to combine. Movie information has been observed.

```{r}
lotr_df =
  bind_rows(fellowship_df, two_towers_df, return_of_king_df) |> 
  janitor::clean_names() |> 
  pivot_longer(
    male:female,
    names_to = "gender",
    values_to = "word"
  ) |> 
  relocate(movie)

```







